#!/bin/zsh
# Builds the native helper into an installer package for JumpCloud to deploy.
#
# Usage:  scripts/build-pkg.sh [version]
#
# The package installs two things, both machine-wide so every user and every
# Chrome profile on the Mac picks them up:
#
#   /Library/Application Support/Hexany/BoxReveal/BoxRevealHost
#   /Library/Google/Chrome/NativeMessagingHosts/com.hexany.boxreveal.json
#
# The package is deliberately unsigned. Gatekeeper only blocks files carrying a
# quarantine flag, which is set by browsers and other downloaders — not by a root
# process installing from a management system. Signing would need a paid Apple
# Developer account and buys nothing for MDM delivery. Do NOT hand this .pkg to
# someone to download and double-click: that path IS quarantined and will be
# blocked.

set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
HOST="$REPO/host"
DIST="$REPO/docs"
PACKAGING="$REPO/packaging"

VERSION="${1:-1.0.0}"
EXT_ID="icplppogbjgfihkpbdcgdhbjekbkmagp"
PKG_ID="com.hexany.boxreveal"
BASE_URL="https://hexanyaudio.github.io/box-assistant"

INSTALL_DIR="/Library/Application Support/Hexany/BoxReveal"
MANIFEST_DIR="/Library/Google/Chrome/NativeMessagingHosts"

# Deployment fleet is mixed Intel and Apple Silicon. `swift build --arch a --arch b`
# needs full Xcode, which build machines here don't have, so build each slice
# separately against the Command Line Tools and lipo them together.
DEPLOY_TARGET="macosx13.0"

print "building arm64…"
(cd "$HOST" && swift build -c release --triple "arm64-apple-$DEPLOY_TARGET" >/dev/null)
print "building x86_64…"
(cd "$HOST" && swift build -c release --triple "x86_64-apple-$DEPLOY_TARGET" >/dev/null)

STAGE=$(mktemp -d)
trap 'rm -rf "$STAGE"' EXIT
PAYLOAD="$STAGE/payload"
mkdir -p "$PAYLOAD$INSTALL_DIR" "$PAYLOAD$MANIFEST_DIR"

BIN="$PAYLOAD$INSTALL_DIR/BoxRevealHost"
lipo -create -output "$BIN" \
  "$HOST/.build/arm64-apple-macosx/release/BoxRevealHost" \
  "$HOST/.build/x86_64-apple-macosx/release/BoxRevealHost"

# Apple Silicon refuses to exec an unsigned binary, so an ad-hoc signature is the
# minimum — and lipo invalidates the per-slice signatures anyway.
codesign --force --sign - "$BIN"
chmod 755 "$BIN"

# Only the packaged extension is allowed. The development identity that
# install-host.sh also permits is deliberately left out of the deployed build.
cat > "$PAYLOAD$MANIFEST_DIR/$PKG_ID.json" <<JSON
{
  "name": "$PKG_ID",
  "description": "Reveals Box items in Finder via Box Drive",
  "path": "$INSTALL_DIR/BoxRevealHost",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://$EXT_ID/"
  ]
}
JSON
chmod 644 "$PAYLOAD$MANIFEST_DIR/$PKG_ID.json"

python3 -c "import json;json.load(open('$PAYLOAD$MANIFEST_DIR/$PKG_ID.json'))"

mkdir -p "$DIST" "$PACKAGING"
PKG="$DIST/BoxRevealHost.pkg"
rm -f "$PKG"

# --ownership recommended installs as root:wheel regardless of who built it.
pkgbuild \
  --root "$PAYLOAD" \
  --identifier "$PKG_ID" \
  --version "$VERSION" \
  --install-location / \
  --ownership recommended \
  "$PKG" >/dev/null

SHA=$(shasum -a 256 "$PKG" | cut -d' ' -f1)

# The deploy script is generated rather than hand-maintained so the checksum can
# never drift from the package it is meant to verify.
cat > "$PACKAGING/jumpcloud-install.sh" <<SCRIPT
#!/bin/bash
# Installs the Box "Reveal in Finder" helper. Run as root via JumpCloud.
# Generated by scripts/build-pkg.sh — do not edit by hand.
set -euo pipefail

URL="$BASE_URL/BoxRevealHost.pkg"
EXPECTED="$SHA"
VERSION="$VERSION"

TMP=\$(mktemp -d)
trap 'rm -rf "\$TMP"' EXIT

curl -fsSL "\$URL" -o "\$TMP/BoxRevealHost.pkg"

# The package is fetched over the public internet, so verify it before running an
# installer as root.
ACTUAL=\$(shasum -a 256 "\$TMP/BoxRevealHost.pkg" | cut -d' ' -f1)
if [ "\$ACTUAL" != "\$EXPECTED" ]; then
  echo "checksum mismatch - refusing to install" >&2
  echo "  expected \$EXPECTED" >&2
  echo "  got      \$ACTUAL" >&2
  exit 1
fi

installer -pkg "\$TMP/BoxRevealHost.pkg" -target / >/dev/null
echo "installed BoxRevealHost \$VERSION"
SCRIPT
chmod +x "$PACKAGING/jumpcloud-install.sh"

print ""
print "package : $PKG  ($(du -h "$PKG" | cut -f1 | tr -d ' '))"
print "version : $VERSION"
print "chips   : $(lipo -archs "$BIN")"
print "sha256  : $SHA"
print ""
print "deploy script: $PACKAGING/jumpcloud-install.sh"
print "package URL  : $BASE_URL/BoxRevealHost.pkg"
