#!/bin/bash
# Installs the Box "Reveal in Finder" helper. Run as root via JumpCloud.
# Generated by scripts/build-pkg.sh — do not edit by hand.
set -euo pipefail

URL="https://hexanyaudio.github.io/box-assistant/BoxRevealHost.pkg"
EXPECTED="8708f15b7057ad765748d5e23b3b9cacadcb4bad8f6f9d856cf5cc321ec07a84"
VERSION="1.0.0"

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

curl -fsSL "$URL" -o "$TMP/BoxRevealHost.pkg"

# The package is fetched over the public internet, so verify it before running an
# installer as root.
ACTUAL=$(shasum -a 256 "$TMP/BoxRevealHost.pkg" | cut -d' ' -f1)
if [ "$ACTUAL" != "$EXPECTED" ]; then
  echo "checksum mismatch - refusing to install" >&2
  echo "  expected $EXPECTED" >&2
  echo "  got      $ACTUAL" >&2
  exit 1
fi

installer -pkg "$TMP/BoxRevealHost.pkg" -target / >/dev/null
echo "installed BoxRevealHost $VERSION"
